src/Config/MediaBundle/Entity/Media.php
<?php

namespace Config\MediaBundle\Entity;

use Config\MediaBundle\Lib\FileManager;
use Config\MediaBundle\Model\File;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Translatable\Translatable;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Bridge\Doctrine\Validator\Constraints as DoctrineAssert;
use JMS\Serializer\Annotation\Groups;
use JMS\Serializer\Annotation\VirtualProperty as VirtualProperty;
/**
 * Class Media
 * @package Config\Media\Entity
 * @ORM\HasLifecycleCallbacks
 * @ORM\Table(name="media")
 * @DoctrineAssert\UniqueEntity(fields="name", message="This name already exists")
 * @ORM\Entity(repositoryClass="Config\MediaBundle\Entity\Repository\MediaRepository")
 * @Gedmo\TranslationEntity(class="Config\MediaBundle\Entity\Translations\MediaTranslations")
 */
class Media extends File  implements  Translatable
{
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string $name
     * @ORM\Column(type="string", unique=true, length=255, nullable=false)
     */
    protected $name;

    /**
     * @var string $realName
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    protected $realName;

    /**
     * @var string $title
     * @Gedmo\Translatable
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $title;

    /**
     * @var string $description
     * @Gedmo\Translatable
     * @ORM\Column(type="text", nullable=true)
     */
    protected $description;

    /**
     * @var string $caption
     * @Gedmo\Translatable
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $caption;

    /**
     * @var string $alt
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $alt;

    /**
     * @var integer $width
     * @ORM\Column(type="integer",length=11, nullable=true)
     */
    protected $width;

    /**
     * @var integer $height
     * @ORM\Column(type="integer",length=11, nullable=true)
     */
    protected $height;

    /**
     * @var string $size
     * @ORM\Column(type="string",length=50, nullable=true)
     */
    protected $size;

    /**
     * @var string $type
     * @ORM\Column(type="string", length=180, nullable=true)
     */
    protected $type;

    /**
     * @var string $icon
     * @ORM\Column(type="string",length=100, nullable=true)
     */
    protected $icon = '';

    /**
     * @var integer $position
     * @ORM\Column(type="integer",length=11, nullable=true)
     */
    protected $position = 0;
    
    /**
     * @Groups({"filter"})
     * @var string $path
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $path;

    /**
     * @var string $context
     * @ORM\Column(type="string", length=155, nullable=true)
     */
    protected $context;

    /**
     * @var $gallery
     * @ORM\ManyToMany(targetEntity="Gallery", mappedBy="media",  cascade={"persist"})
     */
    protected $gallery;

    protected $cropSize;

    /**
     * @var \DateTime $created
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @var \DateTime $updated
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updated;

    /**
     * @ORM\OneToMany(targetEntity="Config\MediaBundle\Entity\Translations\MediaTranslations", mappedBy="object", cascade={"persist", "remove"})
     */
    protected $translations;

    /**
     * @Gedmo\Locale
     * Used locale to override Translation listener`s locale
     * this is not a mapped field of entity metadata, just a simple property
     */
    private $locale;
    
    public function __toString()
    {
        return ($this->name) ? $this->name : '';
    }

    protected function getUploadRootDir()
    {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__.'/../../../../web/'.FileManager::getUploadDir();
    }

    public function getAbsolutePath()
    {
        return null === $this->path
            ? null
            : $this->getUploadRootDir().'/'.$this->path;
    }

    public function getAbsoluteCropPath($size,$name)
    {
        return null === $this->path
            ? null
            : '/'.  $this->getUploadRootDir().'/'.$size.'_'.$name;
    }

    public function getAbsoluteCropWebPath($size,$name)
    {
        return null === $this->path
            ? null
            : '/'.  FileManager::getUploadDir().'/'.$size.'_'.$name;
    }


    public function getWebPath()
    {
        return null === $this->path
            ? null
            : '/'.FileManager::getUploadDir().'/'.$this->path;
    }
    
    public function isMedia(){
        return true;
    }

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     * @throws \Exception
     */
    public function setFile( $file = null)
    {
        if($file->getError()){
            throw new \Exception('Something went wrong!');
        }
        $this->file = $file;
        if (isset($this->path)) {
            $this->temp = $this->path;
            $this->path = null;
        } else {
            $this->path = 'initial';
        }
    }

    protected function setParameters()
    {
        $path = $this->file;
        $file_extension = $this->getFile()->guessExtension();
        if($file_extension == NULL){
            $extension =  explode('.',$this->getFile()->getClientOriginalName());
            $file_extension = end($extension);
        }
        $extensions = FileManager::getExtensions();
        $icons = $this->getFileIcons();
        list($width,$height) = getimagesize($path);
        $finfo = finfo_open(FILEINFO_MIME_TYPE);
        $mtype = finfo_file($finfo, $path);
        
        $this->setType($mtype);
        $this->setWidth($width);
        $this->setHeight($height);

        if(filesize($path) > 1024 * 1024){
            $this->setSize(round(filesize($path) / pow(10,6),2)." mb");
        }
        else{
            $this->setSize(round(filesize($path) / pow(10,3),2)." kb");
        }
        $file_type = explode('/',$mtype);
       
        $this->setIcon($icons[$file_extension]);

    }

    public function getContexts()
    {
        return FileManager::getCropImageSettings();
    }

    protected function checkCropSize($contexts)
    {
        if(array_key_exists ($this->context, $contexts)){
            $this->cropSize = $contexts[$this->context];
        }
        else{
            $this->cropSize = null;
        }
    }


    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {

        if (null !== $this->getFile()) {
            $this->setParameters();
            // do whatever you want to generate a unique name
            $filename = sha1(uniqid(mt_rand(), true));
            $this->path = $filename.'.'.$this->getFile()->guessExtension();
            $originalName = substr ($this->file->getClientOriginalName(), 0, strrpos($this->file->getClientOriginalName(), '.'));
            $this->setRealName($originalName);
            //$em = $this->container->get('doctrine')->getManager();
            $now =  new \DateTime();
            $date = $now->format('dmYHi').mt_rand(100, 9999);
            $this->setName($originalName.$date.'.'.$this->getFile()->guessExtension());
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {

        if (null === $this->getFile()) {
            return;
        }
        $this->checkCropSize($this->getContexts());
        $size = $this->cropSize['formats'];
        $size['admin_thumb'] = array('width'=> 150,'quality'=>70);
        $newFile = $this->getName();
        $this->getFile()->move($this->getUploadRootDir(), $this->path);
        $path = $this->getUploadRootDir().'/'.$this->path;

        foreach($size as $key=>$value){
            $newPath = $this->getUploadRootDir().'/'.$key.'_'.$newFile;
                $this->imageResize(
                $path,
                $newPath,
                $value['width'],
                null,
                $value['quality']
            );
        }

        if (isset($this->temp)) {
            // delete the old image
            unlink($this->getUploadRootDir().'/'.$this->temp);
            // clear the temp image path
            $this->temp = null;
        }
        $this->file = null;
    }


    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        $this->checkCropSize($this->getContexts());
        $size = $this->cropSize['formats'];
        $type = array_keys($size);
        array_push($type,'admin_thumb');
        
        $file = $this->getAbsolutePath();

        if(file_exists($file)){
            $name = $this->name;
            foreach($type as $value){
                if(file_exists($this->getAbsoluteCropPath($value,$name))){
                    unlink($this->getAbsoluteCropPath($value,$name));
                }
            }
        }

        if ($file) {
            unlink($file);
        }
    }


    function imageResize($path,$newPath,$width,$height,$quality)
    {
        if($path){
            ini_set("gd.jpeg_ignore_warning", 1);

            list($w_i, $h_i, $type) = getimagesize($path);
            if (!$w_i || !$h_i) {
                return;
            }
            if($w_i <  $width ){
                return;
            }
            $types = array('','gif','jpeg','png');

            $ext = $types[$type];
            if ($ext) {
                $func = 'imagecreatefrom'.$ext;
                $img = $func($path);
            } else {
                return;

src/Config/MediaBundle/Resources/views/file_count.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field%}
    {{ object.media | length }}
{% endblock %}

src/Config/MediaBundle/Resources/views/list_image.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field%}
    <div class="file_block clear">
        {% set type = object.type|split('/') %}
        {% if type[0] == 'image' %}
            <div style="float: left;margin-right: 15px">
                <img src="{{ media(object,'admin_thumb')  }}">
            </div>
        {% else %}
            <div class="list_image_block">
                <object  data="{{ asset(object.icon) }}" type="image/svg+xml"></object>
            </div>
        {% endif %}
        <div class="left_block info_block">
            <div class="name">
                <p><strong><a href="{{ path('admin_config_media_media_edit',{'id':object.id}) }}">{{ object.realName }}</a></strong></p>
            </div>
            <div class="info">
                <ul>
                    {% if object.width or object.height  %}
                        <li>width: {{ object.width ~ "px"}}</li>
                        <li>height: {{object.height ~ "px "}}</li>
                    {% endif %}
                    <li>Size: {{ object.size }}</li>
                    {#<li>ContentType: {{ object.type }}</li>
                    <li>URL: {{ app.request.getSchemeAndHttpHost()~object.webPath }}</li>#}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

src/Config/MediaBundle/Resources/views/mosaic_list.html.twig
{% extends 'SonataAdminBundle:CRUD:list_outer_rows_mosaic.html.twig' %}

{% block sonata_mosaic_background %}
    <div style="background: url('{{ media(object,'admin_thumb')  }}') no-repeat;width: 160px;height: 150px;background-size: cover;background-position: top center;float: left;margin-right: 15px"></div>
{% endblock %}


{% block sonata_mosaic_default_view %}
    <span class="label label-primary pull-right">{{ object.providerName|trans({}, 'SonataMediaBundle') }}</span>
{% endblock %}

{% block sonata_mosaic_hover_view %}
    <span class="label label-primary pull-right">{{ object.providerName|trans({}, 'SonataMediaBundle') }}</span>

    {% if object.width %} {{ object.width }}{% if object.height %}x{{ object.height }}{% endif %}px{% endif %}
    {% if object.length > 0 %}
        ({{ object.length }})
    {% endif %}

    <br />

    {% if object.authorname is not empty %}
        {{ object.authorname }}
    {% endif %}

    {% if object.copyright is not empty and object.authorname is not empty %}
        ~
    {% endif %}

    {% if object.copyright is not empty %}
        &copy; {{ object.copyright }}
    {% endif  %}
{% endblock %}

{% block sonata_mosaic_description %}
    {% if admin.isGranted('EDIT', object) and admin.hasRoute('edit') %}
        <a href="{{ admin.generateUrl('edit', {'id' : object|sonata_urlsafeid(admin) }) }}">{{ meta.title|truncate(40) }}</a>
    {% elseif admin.isGranted('SHOW', object) and admin.hasRoute('show') %}
        <a href="{{ admin.generateUrl('show', {'id' : object|sonata_urlsafeid(admin) }) }}">{{ meta.title|truncate(40) }}</a>
    {% else %}
        {{ meta.title|truncate(40) }}
    {% endif %}
{% endblock %}